# Generated by Django 4.2.1 on 2023-05-21 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('UCH', 'Учебная'), ('DOP', 'Дополнительная'), ('RAZ', 'Развлекающая')], default='UCH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEducations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_edu', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age_kids', models.PositiveIntegerField(default=0)),
                ('max_age_kids', models.IntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)])),
                ('about', models.TextField(blank=True)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.photoeducations')),
                ('type_edu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.categories')),
            ],
        ),
    ]
