# Generated by Django 4.2.1 on 2023-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_categories_options_alter_educations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='educations',
            options={'ordering': ['id'], 'verbose_name': 'Программу', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='photoeducations',
            options={'verbose_name': 'Фото программы', 'verbose_name_plural': 'Фото программ'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='type_name',
            field=models.CharField(choices=[('UCH', 'Учебная'), ('DOP', 'Дополнительная'), ('RAZ', 'Развлекающая')], default='UCH', max_length=3, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='photoeducations',
            name='name_edu',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photoeducations',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
